version: "3.8"

services:
  clean-node-api:
    depends_on:
      - db
    image: clean-node-api
    container_name: clean-node-api
    build:
      dockerfile: docker/dev/Dockerfile
      context: .
    stdin_open: true
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}:/app"
      - "/app/node_modules"
    networks:
      - clean-node-api

  db:
    image: postgres:15-alpine
    networks:
      - clean-node-api
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  clean-node-api:
    external: true
